### ISSUE TITLE
Multiple errors while running tests

### ISSUE THREAD

**Issue by eclipseo** [ocaml-ppx/ppx_deriving#216]
Fedora Rawhide with ocaml-4.10.0 and ocaml-dune-2.4.0:

```
+ dune runtest
File "src_test/deriving/test_ppx_deriving.ml", line 4, characters 25-35:
4 |   let sort = List.sort [%derive.ord: int * int] in
                             ^^^^^^^^^^
Error: Uninterpreted extension 'derive.ord'.
File "src_test/create/test_deriving_create.ml", line 38, characters 24-32:
38 |   assert_equal ~printer:M.show_a
                             ^^^^^^^^
Error: Unbound value M.show_a
File "src_test/enum/test_deriving_enum.ml", line 7, characters 42-52:
7 |   assert_equal ~printer:string_of_int 0  (va_to_enum Aa);
                                              ^^^^^^^^^^
Error: Unbound value va_to_enum
File "test_deriving_fold.cppo.ml", line 8, characters 41-51:
Error: Unbound value fold_btree
File "src_test/make/test_deriving_make.ml", line 48, characters 24-32:
48 |   assert_equal ~printer:M.show_a
                             ^^^^^^^^
Error: Unbound value M.show_a
File "test_deriving_eq.cppo.ml", line 24, characters 31-39:
Error: Unbound value equal_a1
File "test_deriving_iter.cppo.ml", line 34, characters 2-12:
Error: Unbound value iter_btree
File "test_deriving_ord.cppo.ml", line 22, characters 30-40:
Error: Unbound value compare_a1
Hint: Did you mean compare?
File "test_deriving_show.cppo.ml", line 23, characters 35-42:
Error: Unbound value show_a1
File "test_deriving_map.cppo.ml", line 81, characters 15-24:
Error: Unbound value map_btree
```

**Comment by chrismamo1** [comment]
Can you provide some more information? Perhaps the `dune` file you were using?

**Comment by kit-ty-kate** [comment]
```
FROM ocaml/opam:fedora-ocaml-4.10
RUN opam install --with-test --deps ppx_deriving dune.2.4.0
RUN opam source ppx_deriving
WORKDIR ppx_deriving.5.2.1
```
works fine on fedora and dune 2.4.0 and I haven't been able to find the original failure in the Fedora bugtracker, so closing. Feel free to reopen if you can provide a reproduction case.
